server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable?serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: 123456
flowable:
  async-executor-activate: true  # 关闭定时任务JOB
  database-schema-update: true   # 为true时，当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本
  mail:
    server:
      default-from: 18200000000@163.com
      host: smtp.163.com
      username: 18200000000@163.com
      password: 163邮箱授权码
      s-s-l-port: 465
      use-ssl: true
      use-tls: true
      default-charset: utf-8
logging:
  level:
    root: warn


